/*******************************************************************************
 * Autogenerated by MCALgen for MCAL V2.0.0.30631: Can.c
 *******************************************************************************/
 /* [$Satisfies $CAN 1003] */
 /* [$Satisfies $CAN 1004] */
/************************************************************************************************************
 *                              Include Files
 ***********************************************************************************************************/
#include "Can.h"
#include "Can_Implementation.h"

/* [$CAN 1012] [$CAN 111] [$CAN 1178] */
/* Version checks */
#if (CAN_AR_RELEASE_MAJOR_VERSION != (4U)) || (CAN_AR_RELEASE_MINOR_VERSION != (2U)) || (CAN_AR_RELEASE_REVISION_VERSION != (2U))
 #error "CAN AUTOSAR version in CAN.h does not match 4.2.2"
#endif
#if (CAN_SW_MAJOR_VERSION != (1U)) || (CAN_SW_MINOR_VERSION != (0U)) || (CAN_SW_PATCH_VERSION != (54U))
 #error "CAN software version in CAN.h does not match 1.0.54"
#endif
#if (CAN_VENDOR_ID !=  (11U))
 #error "CAN Vendor ID in CAN.h does not match 11"
#endif


#if (CAN_DEV_ERROR_DETECT == STD_ON)
 #include "Det.h"
#endif

/* [$CAN 394] */
/*----------------------------
 * Start of const
 *----------------------------*/
#define CAN_START_SEC_CONST_UNSPECIFIED
#include "Can_MemMap.h"

/*----------------------------
 * End of const
 *----------------------------*/
#define CAN_STOP_SEC_CONST_UNSPECIFIED
#include "Can_MemMap.h"

/*----------------------------
 * Start of code
 *----------------------------*/
#define CAN_START_SEC_CODE
#include "Can_MemMap.h"

/******************************************************************************
* Can_Init
******************************************************************************/
void Can_Init(const Can_ConfigType* Config) { /* [$CAN 223] [$CAN 386]*/
  Can_Init_helper(Config);
}

/******************************************************************************
* Can_InitController 4.0.2 support
******************************************************************************/
void Can_InitController(uint8 Controller, const Can_ControllerBaudrateConfigType* Config) { /* [$CAN 1102] */
  Can_InitController_helper(Controller, Config);
}

/******************************************************************************
* Can_GetVersionInfo
******************************************************************************/
#if(CAN_VERSION_INFO_API == STD_ON) /* [$CAN 252] */
void Can_GetVersionInfo(Std_VersionInfoType* versioninfo) { /* [$CAN 224] [$CAN 386]  */
 Can_GetVersionInfo_helper(versioninfo);
}
#endif

 /* [$CAN 1253] [$CAN 1254] */
 /* [$CAN 1253] [$CAN 1254] */
/******************************************************************************
* Can_CheckBaudrate
******************************************************************************/
#if(CAN_CHANGE_BAUDRATE_API == STD_ON) /* [$CAN 460] */
Std_ReturnType Can_CheckBaudrate(uint8 Controller, const uint16 Baudrate) {  /* [$CAN 454] */
  return Can_CheckBaudrate_helper(Controller, Baudrate);
}
#endif

/******************************************************************************
* Can_ChangeBaudrate
******************************************************************************/
#if(CAN_CHANGE_BAUDRATE_API == STD_ON) /* [$CAN 460] */
Std_ReturnType Can_ChangeBaudrate(uint8 Controller, const uint16 Baudrate) { /* [$CAN 449] */
  return Can_ChangeBaudrate_helper(Controller, Baudrate, CAN_CHANGEBAUDRATE_API_ID);
}
#endif

/******************************************************************************
* Can_SetControllerMode
******************************************************************************/
Can_ReturnType Can_SetControllerMode(uint8 Controller, Can_StateTransitionType Transition) {
  return Can_SetControllerMode_helper(Controller, Transition, FALSE);
}




/******************************************************************************
* Can_DisableControllerInterrupts
******************************************************************************/
void Can_DisableControllerInterrupts(uint8 Controller) { /* [$CAN 231] */
  Can_DisableControllerInterrupts_helper(Controller);
}

/******************************************************************************
* Can_EnableControllerInterrupts
******************************************************************************/
void Can_EnableControllerInterrupts(uint8 Controller) { /* [$CAN 232] */
  Can_EnableControllerInterrupts_helper(Controller);
}

/******************************************************************************
* Can_CheckWakeup
******************************************************************************/

#if(CAN_CHECKWAKEUP_API == STD_ON)
Can_ReturnType Can_CheckWakeup(uint8 Controller) { /* [$CAN 360] */
  return Can_CheckWakeup_helper(Controller);
}
#endif

/******************************************************************************
* Can_Write
******************************************************************************/

Can_ReturnType Can_Write(Can_HwHandleType Hth, const Can_PduType* PduInfo) { /* [$CAN 233] */
  return Can_Write_helper(Hth, PduInfo, TRUE, FALSE);/* [$CAN 233] */
}

/******************************************************************************
* Can_MainFunction_Write
******************************************************************************/
void Can_MainFunction_Write(void) { /* [$CAN 225] */
  Can_MainFunction_Write_helper(FALSE);
}

/******************************************************************************
* Can_MainFunction_Read
******************************************************************************/
void Can_MainFunction_Read(void) { /* [$CAN 226] */
  Can_MainFunction_Read_helper(FALSE);
}

/******************************************************************************
* Can_MainFunction_BusOff
******************************************************************************/
void Can_MainFunction_BusOff(void) { /* [$CAN 227] */
  Can_MainFunction_BusOff_helper(FALSE);
}

/******************************************************************************
* Can_MainFunction_Wakeup
******************************************************************************/
void Can_MainFunction_Wakeup(void) { /* [$CAN 228] */
  Can_MainFunction_Wakeup_helper(FALSE);
}

/******************************************************************************
* Can_MainFunction_Mode
******************************************************************************/
void Can_MainFunction_Mode(void) { /* [$CAN 368] */
  Can_MainFunction_Mode_helper();
}

/******************************************************************************
 * Apis introduced from AUTOSAR 4.1.1 onwards
******************************************************************************/
/* [$CAN 1225] [$CAN 1224] */
/******************************************************************************
* Can_SetBaudrate * AR 4.2.1 specific api
******************************************************************************/
#if(CAN_CHANGE_BAUDRATE_API == STD_ON) /* [$CAN  1221] */
Std_ReturnType Can_SetBaudrate(uint8 Controller, const uint16 BaudRateConfigID) { /* [$CAN 1130] */
  return Can_ChangeBaudrate_helper(Controller, BaudRateConfigID, CAN_SETBAUDRATE_API_ID);
}
#endif

/******************************************************************************
* Can_SetIcomConfiguration * AR 4.2.1 specific api
******************************************************************************/
Std_ReturnType Can_SetIcomConfiguration(uint8 Controller, IcomConfigIdType ConfigurationId) { /* [$CAN 1125] [$CAN 1151] */
  return E_OK;
}

/******************************************************************************
* AR 4.3.1 specific api
******************************************************************************/
  
/*----------------------------
 * End of code
 *----------------------------*/
#define CAN_STOP_SEC_CODE
#include "Can_MemMap.h"


