/* [$CAN 35]*/
/*******************************************************************************
 * Autogenerated by MCALgen for CAN V1.0.54.30643: Can_Irq.c
 *******************************************************************************/
 /* [$Satisfies $CAN 1003] */
 /* [$Satisfies $CAN 1004] */

/************************************************************************************************************
 *                              Include Files
 ***********************************************************************************************************/
#include "Can.h"
#include "Can_Implementation.h"
#include "Os.h"

/* [$CAN 1012] [$CAN 111] */
/* Version checks */
#if (CAN_AR_RELEASE_MAJOR_VERSION != (4U)) || (CAN_AR_RELEASE_MINOR_VERSION != (2U)) || (CAN_AR_RELEASE_REVISION_VERSION != (2U))
 #error "CAN AUTOSAR version in CAN.h does not match 4.2.2"
#endif
#if (CAN_SW_MAJOR_VERSION != (1U)) || (CAN_SW_MINOR_VERSION != (0U)) || (CAN_SW_PATCH_VERSION != (54U))
 #error "CAN software version in CAN.h does not match 1.0.54"
#endif
#if (CAN_VENDOR_ID !=  (11U))
 #error "CAN Vendor ID in CAN.h does not match 11"
#endif


/*----------------------------
 * Start of code
 *----------------------------*/
#define CAN_START_SEC_CODE
#include "Can_MemMap.h"
/* [$CAN 33]  */
ISR(Can_IrqHandler) {
  Can_Isr_handler();
}


/*----------------------------
 * End of code
 *----------------------------*/
#define CAN_STOP_SEC_CODE
#include "Can_MemMap.h"


