/*******************************************************************************
 * Autogenerated by MCALgen for CAN V1.0.54.30643: Fls.c
 *******************************************************************************/

/************************************************************************************************************
 *                              Include Files
 ***********************************************************************************************************/
#include "Fls.h"
#include "Fls_Implementation.h"
#if (FLS_DEV_ERROR_DETECT == STD_ON)
  #include "Det.h"
#endif
#include "Fls_Device.h"
/* [$Fls 1020] */
/* Version checks */
#if (FLS_AR_RELEASE_MAJOR_VERSION != (4U)) || (FLS_AR_RELEASE_MINOR_VERSION != (2U)) || (FLS_AR_RELEASE_REVISION_VERSION != (2U))
 #error "FLS AUTOSAR version in FLS.h does not match 4.2.2"
#endif
#if (FLS_SW_MAJOR_VERSION != (1U)) || (FLS_SW_MINOR_VERSION != (0U)) || (FLS_SW_PATCH_VERSION != (54U))
 #error "FLS software version in FLS.h does not match 1.0.54"
#endif
#if (FLS_VENDOR_ID !=  (11U))
 #error "FLS Vendor ID in FLS.h does not match 11"
#endif


/*----------------------------
 * Start of const
 *----------------------------*/
#define FLS_START_SEC_CONST_UNSPECIFIED
#include "Fls_MemMap.h"
/*----------------------------
 * End of const
 *----------------------------*/
#define FLS_STOP_SEC_CONST_UNSPECIFIED
#include "Fls_MemMap.h"

/*----------------------------
 * Start of code
 *----------------------------*/
#define FLS_START_SEC_CODE
#include "Fls_MemMap.h"


/******************************************************************************
* Fls_Init
******************************************************************************/
void Fls_Init(const Fls_ConfigType* ConfigPtr) { /* [$Fls 249] */
  Fls_Init_helper(ConfigPtr, FALSE);
}

/******************************************************************************
* Fls_Erase
******************************************************************************/
Std_ReturnType Fls_Erase(Fls_AddressType TargetAddress, Fls_LengthType Length) { /* [$Fls 250] */
  return Fls_Erase_helper(TargetAddress, Length, FALSE);
}

/******************************************************************************
* Fls_Write
******************************************************************************/
Std_ReturnType Fls_Write(Fls_AddressType TargetAddress, const uint8* SourceAddressPtr, Fls_LengthType Length) {  /* [$Fls 251] */
  return Fls_Write_helper(TargetAddress, SourceAddressPtr, Length, FALSE);
}

/******************************************************************************
* Fls_Cancel
******************************************************************************/
#if (FLS_CANCEL_API == STD_ON)
void Fls_Cancel(void) { /* [$Fls 252] */
  Fls_Cancel_helper(FALSE);
}
#endif

/******************************************************************************
* Fls_GetStatus
******************************************************************************/
#if (FLS_GET_STATUS_API == STD_ON)
MemIf_StatusType Fls_GetStatus(void) { /* [$Fls 253] */
  return Fls_GetStatus_helper();
}
#endif

/******************************************************************************
* Fls_GetJobResult
******************************************************************************/
#if (FLS_GET_JOB_RESULT_API == STD_ON)
MemIf_JobResultType Fls_GetJobResult(void) { /* [$Fls 254] */
  return Fls_GetJobResult_helper(FALSE);
}
#endif

/******************************************************************************
* Fls_Read
******************************************************************************/
Std_ReturnType Fls_Read(Fls_AddressType SourceAddress, uint8* TargetAddressPtr, Fls_LengthType Length) { /* [$Fls 256] */
  return Fls_Read_helper(SourceAddress, TargetAddressPtr, Length, FALSE);
}

/******************************************************************************
* Fls_Compare
******************************************************************************/
#if (FLS_COMPARE_API == STD_ON)
Std_ReturnType Fls_Compare(Fls_AddressType SourceAddress, const uint8* TargetAddressPtr, Fls_LengthType Length) { /* [$Fls 257] */
  return Fls_Compare_helper(SourceAddress, TargetAddressPtr, Length, FALSE);
}
#endif

/******************************************************************************
* Fls_SetMode
******************************************************************************/
#if (FLS_SET_MODE_API == STD_ON)
void Fls_SetMode(MemIf_ModeType Mode) { /* [$Fls 258] */
  Fls_SetMode_helper(Mode, FALSE);
}
#endif

/******************************************************************************
* Fls_GetVersionInfo
******************************************************************************/
#if (FLS_VERSION_INFO_API == STD_ON)
void Fls_GetVersionInfo(Std_VersionInfoType* VersioninfoPtr) { /* [$Fls 259] */
  Fls_GetVersionInfo_helper(VersioninfoPtr, FALSE);
}
#endif

/******************************************************************************
* Fls_MainFunction
******************************************************************************/
void Fls_MainFunction(void) { /* [$Fls 255] */
  Fls_MainFunction_helper(FALSE);
}

 /* [$Fls 1235] */
/******************************************************************************
* Fls_BlankCheck
******************************************************************************/
Std_ReturnType Fls_BlankCheck(Fls_AddressType TargetAddress, Fls_LengthType Length) { /* [$Fls 1234] [$Fls 1252] */
  return Fls_BlankCheck_helper(TargetAddress, Length, FALSE);
}
  
  
/*----------------------------
 * End of code
 *----------------------------*/
#define FLS_STOP_SEC_CODE
#include "Fls_MemMap.h"


