/*******************************************************************************
 * Autogenerated by MCALgen for FLS V1.0.54.30643: Fls_Lcfg.c
 *******************************************************************************/
 #include "Fls.h"

/* [$Fls 1020] */
/* Version checks */
#if (FLS_AR_RELEASE_MAJOR_VERSION != (4U)) || (FLS_AR_RELEASE_MINOR_VERSION != (2U)) || (FLS_AR_RELEASE_REVISION_VERSION != (2U))
 #error "FLS AUTOSAR version in FLS.h does not match 4.2.2"
#endif
#if (FLS_SW_MAJOR_VERSION != (1U)) || (FLS_SW_MINOR_VERSION != (0U)) || (FLS_SW_PATCH_VERSION != (54U))
 #error "FLS software version in FLS.h does not match 1.0.54"
#endif
#if (FLS_VENDOR_ID !=  (11U))
 #error "FLS Vendor ID in FLS.h does not match 11"
#endif


