/*******************************************************************************
 * Autogenerated by MCALgen for FLS V1.0.54.30643: Fls_Cfg.h
 *******************************************************************************/
#ifndef FLS_CFG_H_
#define FLS_CFG_H_

extern uint32* Fls_BaseAddress(void);
#define FLS_BASE_ADDRESS			 Fls_BaseAddress() /* [$Fls 9169] */
#define FLS_DRIVER_INDEX			 (0) /* [$Fls 9288] */
#define FLS_TOTAL_SIZE				 (6144U) /* [$Fls 9170] */
#define FLS_CANCEL_API				 STD_OFF /* [$Fls 183] [$Fls 9285] */
#define FLS_COMPARE_API				 STD_ON /* [$Fls 186] [$Fls 9286] */
#define FLS_DEV_ERROR_DETECT	 STD_OFF /* [$Fls 77] [$Fls 9287] */
#define FLS_GET_JOB_RESULT_API STD_ON /* [$Fls 185] [$Fls 9289] */
#define FLS_GET_STATUS_API		 STD_ON /* [$Fls 184] [$Fls 9290] */
#define FLS_SET_MODE_API		   STD_OFF /* [$Fls 187] [$Fls 9291] */
#define FLS_VERSION_INFO_API	 STD_ON /* [$Fls 166] [$Fls 9293] */

#define FLS_ERASE_VALUE     255
/***********************************************************************************************************
 *				External References
 ***********************************************************************************************************/
extern const Fls_ConfigType FlsConfigData[];
#define FLS_DEFAULT_CONFIG &FlsConfigData[0]





#endif /* FLS_CFG_H_ */

