/*******************************************************************************
 * Autogenerated by MCALgen for FLS V1.0.54.30643: Fls_PBcfg.c
 *******************************************************************************/

/************************************************************************************************************
 *				Include Files
 ***********************************************************************************************************/
#include "Fls.h"

/************************************************************************************************************
 *				Macro Definitions
 ***********************************************************************************************************/
/* [$Fls 1020] */
/* Version checks */
#if (FLS_AR_RELEASE_MAJOR_VERSION != (4U)) || (FLS_AR_RELEASE_MINOR_VERSION != (2U)) || (FLS_AR_RELEASE_REVISION_VERSION != (2U))
 #error "FLS AUTOSAR version in FLS.h does not match 4.2.2"
#endif
#if (FLS_SW_MAJOR_VERSION != (1U)) || (FLS_SW_MINOR_VERSION != (0U)) || (FLS_SW_PATCH_VERSION != (54U))
 #error "FLS software version in FLS.h does not match 1.0.54"
#endif
#if (FLS_VENDOR_ID !=  (11U))
 #error "FLS Vendor ID in FLS.h does not match 11"
#endif


/***********************************************************************************************************
 *				Global Config Data
 ***********************************************************************************************************/
static const Fls_SectorType Fls_SectorList[] = {  /* [$Fls 9201] */
   /* [$Fls 9202] */
  {
  0, /* [$Fls 9283] [$Fls 1109]*/
  8, /* [$Fls 9281]*/
  1024, /* [$Fls 9282]*/
  6, /* [$Fls 9280]*/
  768
  },
 
};



 const Fls_ConfigType FlsConfigData[] = { /* [$Fls 352] [$Fls 353] */
  {
  NULL_PTR,
  NULL_PTR,
  &Fls_SectorList[0], /* FlsSectorList */
  sizeof(Fls_SectorList)/sizeof(Fls_SectorType), /* FlsSectorListSize */
  MEMIF_MODE_SLOW /* InitialMode */
  }
 };

