/*******************************************************************************
 * Autogenerated by MCALgen for FLS V1.0.54.30643: Fls_Implementation.h
 *******************************************************************************/
#ifndef FLS_IMPLEMENTATION_H_
#define FLS_IMPLEMENTATION_H_

#include "Dem.h"

/* [$Fls 9314] [$Fls 9311] [$Fls 9313] [$Fls 9315] [$Fls 9312] */

        
extern Std_ReturnType RaiseDetError(uint32 instance, uint32 api, uint32 err, boolean fromAction);
extern void Fls_Init_helper(const Fls_ConfigType* ConfigPtr, boolean fromAction);
extern Std_ReturnType Fls_Erase_helper(Fls_AddressType TargetAddress, Fls_LengthType Length, boolean fromAction);
extern Std_ReturnType Fls_Write_helper(Fls_AddressType TargetAddress, const uint8* SourceAddressPtr, Fls_LengthType Length, boolean fromAction);
extern void Fls_Cancel_helper(boolean fromAction);
extern MemIf_StatusType Fls_GetStatus_helper(void);
extern MemIf_JobResultType Fls_GetJobResult_helper(boolean fromAction);
extern Std_ReturnType Fls_Read_helper(Fls_AddressType SourceAddress, uint8* TargetAddressPtr, Fls_LengthType Length, boolean fromAction);
extern Std_ReturnType Fls_Compare_helper(Fls_AddressType SourceAddress, const uint8* TargetAddressPtr, Fls_LengthType Length, boolean fromAction);
extern void Fls_SetMode_helper(MemIf_ModeType Mode, boolean fromAction);
extern void Fls_GetVersionInfo_helper(Std_VersionInfoType* VersioninfoPtr, boolean fromAction);
extern void Fls_MainFunction_helper(boolean fromAction);
 /* [$Fls 1235] */
extern Std_ReturnType Fls_BlankCheck_helper(Fls_AddressType TargetAddress, Fls_LengthType Length, boolean fromAction);

#endif /* FLS_IMPLEMENTATION_H_ */


