/*******************************************************************************
 * Autogenerated by MCALgen for FLS V1.0.54.30643: Fls_Device.h
 *******************************************************************************/
#ifndef FLS_DEVICE_H_
#define FLS_DEVICE_H_

extern void Fls_Device_StartJob(uint8 api);
extern void Fls_Device_UpdateJob(void);
extern void Fls_Device_UpdateDet(uint32 instance,uint32 api,uint32 err);
extern void Fls_Device_UpdateDem(Dem_EventIdType EventId, Dem_EventStatusType EventStatus);

#endif /* FLS_DEVICE_H_ */

