/*******************************************************************************
 * Autogenerated by MCALgen for FLS V1.0.54.30643: Fls_Internal.h
 *******************************************************************************/
#ifndef FLS_INTERNAL_H_
#define FLS_INTERNAL_H_

/************************************************************************************************************
 *				Include Files
 ***********************************************************************************************************/
#include "Std_Types.h"
#include "MemIf_Types.h"

/************************************************************************************************************
 *				Data Declarations
 ***********************************************************************************************************/

extern void Fls_InjectHardwareError(int on);
extern int Fls_InternalHardwareErrorState(void);
extern void Fls_InjectEraseVerifyError(int on);
extern int Fls_InternalEraseVerifyErrorState(void);
extern void Fls_InjectBlankCheckVerifyError(int on);
extern int Fls_InternalBlankCheckVerifyErrorState(void);
extern void Fls_InjectWriteVerifyError(int on);
extern int Fls_InternalWriteVerifyErrorState(void);
extern void Fls_InjectReadTimeoutError(int on);
extern int Fls_InternalReadTimeoutErrorState(void);
extern void Fls_InjectWriteTimeoutError(int on);
extern int Fls_InternalWriteTimeoutErrorState(void);
extern void Fls_InjectCompareTimeoutError(int on);
extern int Fls_InternalCompareTimeoutErrorState(void);
extern void Fls_InjectEraseTimeoutError(int on);
extern int Fls_InternalEraseTimeoutErrorState(void);
extern MemIf_JobResultType Fls_InternalJobResult(void);
extern MemIf_StatusType Fls_InternalMemStatus(void);
extern void Fls_SetInternalMemStatus(MemIf_StatusType s);
extern const Fls_ConfigType* Fls_GetInternalConfig(void);
extern MemIf_ModeType Fls_GetInternalMode(void);
extern void Fls_DeAllocateMemory(void);

#endif /* FLS_INTERNAL_H_ */

