/*******************************************************************************
 * Autogenerated by MCALgen for FLS V1.0.54.30643: Mcu.c
 *******************************************************************************/

/************************************************************************************************************
 *                              Include Files
 ***********************************************************************************************************/
#include "Mcu.h" /* [$MCU 108] */
#include "Mcu_Cbk.h" /* [$MCU 219] */
#include "Mcu_Implementation.h"

/* Version checks */
#if (MCU_AR_RELEASE_MAJOR_VERSION != (4U)) || (MCU_AR_RELEASE_MINOR_VERSION != (2U)) || (MCU_AR_RELEASE_REVISION_VERSION != (2U))
 #error "MCU AUTOSAR version in MCU.h does not match 4.2.2"
#endif
#if (MCU_SW_MAJOR_VERSION != (1U)) || (MCU_SW_MINOR_VERSION != (0U)) || (MCU_SW_PATCH_VERSION != (54U))
 #error "MCU software version in MCU.h does not match 1.0.54"
#endif
#if (MCU_VENDOR_ID !=  (11U))
 #error "MCU Vendor ID in MCU.h does not match 11"
#endif
 /* [$MCU 110] */

#if (MCU_DEV_ERROR_DETECT == STD_ON)
 #include "Det.h"
#endif

/*----------------------------
 * Start of code
 *----------------------------*/
#define MCU_START_SEC_CODE
#include "Mcu_MemMap.h"



/******************************************************************************
* Mcu_Init
******************************************************************************/
void Mcu_Init(const Mcu_ConfigType* ConfigPtr) { /* [$MCU 153] */
 Mcu_Init_helper(ConfigPtr, FALSE);
}

/******************************************************************************
* Mcu_InitRamSection
******************************************************************************/
Std_ReturnType Mcu_InitRamSection(Mcu_RamSectionType RamSection) {  /* [$MCU 154] */
  return Mcu_InitRamSection_helper(RamSection, FALSE);
}

/******************************************************************************
* Mcu_InitClock
******************************************************************************/
#if(MCU_INIT_CLOCK == STD_ON) /* [$MCU 210] */
Std_ReturnType Mcu_InitClock(Mcu_ClockType ClockSetting) {  /* [$MCU 155] */
  return Mcu_InitClock_helper(ClockSetting, FALSE);
}
#endif

/******************************************************************************
* Mcu_DistributePllClock
******************************************************************************/
#if(MCU_NO_PLL == FALSE) /* [$MCU 205] */
void Mcu_DistributePllClock(void) {  /* [$MCU 156] */
  Mcu_DistributePllClock_helper(FALSE);
}
#endif

/******************************************************************************
* Mcu_GetPllStatus
******************************************************************************/
Mcu_PllStatusType Mcu_GetPllStatus(void) {  /* [$MCU 157] */
  return Mcu_GetPllStatus_helper(FALSE);
}

/******************************************************************************
* Mcu_GetResetReason
******************************************************************************/
Mcu_ResetType Mcu_GetResetReason(void) {  /* [$MCU 158] */
  return Mcu_GetResetReason_helper(FALSE);
}

/******************************************************************************
* Mcu_GetResetRawValue
******************************************************************************/
Mcu_RawResetType Mcu_GetResetRawValue(void) {  /* [$MCU 159] */
  return Mcu_GetResetRawValue_helper(FALSE);
}

/******************************************************************************
* Mcu_PerformReset
******************************************************************************/
#if(MCU_PERFORM_RESET_API == STD_ON) /* [$MCU 146] */
void Mcu_PerformReset(void) {  /* [$MCU 160] [$MCU 55] */
  Mcu_PerformReset_helper(FALSE);
}
#endif

/******************************************************************************
* Mcu_SetMode
******************************************************************************/
void Mcu_SetMode(Mcu_ModeType McuMode) {  /* [$MCU 161] */
  Mcu_SetMode_helper(McuMode, FALSE);
}

/******************************************************************************
* Mcu_GetVersionInfo
******************************************************************************/
#if(MCU_VERSION_INFO_API == STD_ON) /* [$MCU 104] */
 /* [$MCU 149] Not macro - can't tell if source code is available for caller */
void Mcu_GetVersionInfo(Std_VersionInfoType* versioninfo) {  /* [$MCU 162] */
  Mcu_GetVersionInfo_helper(versioninfo, FALSE);
}
#endif

/******************************************************************************
* Mcu_GetRamState
******************************************************************************/
#if(MCU_GET_RAM_STATE_API  == STD_ON) /* [$MCU 209] */
Mcu_RamStateType Mcu_GetRamState(void) {  /* [$MCU 207] */
  return Mcu_GetRamState_helper(FALSE);
}
#endif


/*----------------------------
 * End of code
 *----------------------------*/
#define MCU_STOP_SEC_CODE
#include "Mcu_MemMap.h"


