/*******************************************************************************
 * Autogenerated by MCALgen for MCU V1.0.54.30643: Mcu_Implementation.h
 *******************************************************************************/
#ifndef MCU_IMPLEMENTATION_H_
#define MCU_IMPLEMENTATION_H_

extern void Mcu_Init_helper(const Mcu_ConfigType *configData, boolean fromAction);
extern Std_ReturnType Mcu_DETError(uint32 instanceId, uint32 apiId, uint32 errorId, boolean fromAction);
extern Std_ReturnType Mcu_InitRamSection_helper(Mcu_RamSectionType RamSection, boolean fromAction);
extern Std_ReturnType Mcu_InitClock_helper(Mcu_ClockType ClockSetting,boolean fromAction);
extern void Mcu_DistributePllClock_helper(boolean fromAction);
extern Mcu_PllStatusType Mcu_GetPllStatus_helper(boolean fromAction);
extern Mcu_ResetType Mcu_GetResetReason_helper(boolean fromAction);
extern Mcu_RawResetType Mcu_GetResetRawValue_helper(boolean fromAction);
extern void Mcu_PerformReset_helper(boolean fromAction);
extern void Mcu_SetMode_helper(Mcu_ModeType McuMode,boolean fromAction);
extern void Mcu_GetVersionInfo_helper(Std_VersionInfoType* VersionInfo,boolean fromAction);
extern Mcu_RamStateType Mcu_GetRamState_helper(boolean fromAction);
extern void Mcu_InjectReset_helper(Mcu_ResetType reset);
extern void Mcu_Raise_ResetReason_event(Mcu_ResetType mcu_reset_reason);
extern uint32 Mcu_ResetCounter_helper(void);

#endif /* MCU_IMPLEMENTATION_H_ */

