/*******************************************************************************
 * Autogenerated by MCALgen for MCU V1.0.54.30643: Mcu_Device.hpp
 *******************************************************************************/
#ifndef MCU_DEVICE_HPP_
#define MCU_DEVICE_HPP_

extern void Mcu_ReportDETError(uint32 instanceId, uint32 apiId, uint32 errorId);


#endif /* MCU_DEVICE_HPP_ */

