/*******************************************************************************
 * Autogenerated by MCALgen for MCU V1.0.54.30643: Mcu_Internal.h
 *******************************************************************************/
#ifndef MCU_INTERNAL_H_
#define MCU_INTERNAL_H_

extern const Mcu_ConfigType* Mcu_GetInternalConfig(void);

#endif /* MCU_INTERNAL_H_ */

