/*******************************************************************************
 * Autogenerated by MCALgen for MCU V1.0.54.30643: Mcu_Cfg.h
 *******************************************************************************/
#ifndef MCU_CFG_H_
#define MCU_CFG_H_

#define MCU_DEFAULT_CONFIG ((const Mcu_ConfigType*) 0)
#define MCU_DEV_ERROR_DETECT STD_OFF /* [$MCU 100] */
#define MCU_NO_PLL  TRUE
#define MCU_INIT_CLOCK STD_ON
#define MCU_PERFORM_RESET_API STD_OFF
#define MCU_GET_RAM_STATE_API STD_OFF
#define MCU_VERSION_INFO_API STD_ON
#define DEFAULT_RESET_RAW_VALUE (0)
#define UNINIT_RESET_RAW_VALUE (0xFFFF)


#define McuConf_McuClockSettingConfig_McuClockSettingConfig_0 (111U)

#define McuConf_McuClockSettingConfig_McuClockSettingConfig_1 (1U)

#define McuConf_McuClockSettingConfig_McuClockSettingConfig_2 (255U)



#define McuConf_McuModeSettingConf_McuModeSettingConf_0 (25U)

#define McuConf_McuModeSettingConf_McuModeSettingConf_2 (150U)

#define McuConf_McuModeSettingConf_McuModeSettingConf_3 (7U)

#define McuConf_McuModeSettingConf_McuModeSettingConf_1 (210U)



#define McuConf_McuResetReasonConf_McuResetReasonConf_0 (0U)

#define McuConf_McuResetReasonConf_McuResetReasonConf_1 (75U)

#define McuConf_McuResetReasonConf_McuResetReasonConf_2 (175U)

  
extern const Mcu_ConfigType Mcu_ConfigData;

#endif /* MCU_CFG_H_ */


