/*******************************************************************************
 * Autogenerated by MCALgen for MCU V1.0.54.30643: Mcu_Irq.c
 *******************************************************************************/

/************************************************************************************************************
 *                              Include Files
 ***********************************************************************************************************/
#include "Mcu.h" /* [$MCU 213] */

/* Version checks */
#if (MCU_AR_RELEASE_MAJOR_VERSION != (4U)) || (MCU_AR_RELEASE_MINOR_VERSION != (2U)) || (MCU_AR_RELEASE_REVISION_VERSION != (2U))
 #error "MCU AUTOSAR version in MCU.h does not match 4.2.2"
#endif
#if (MCU_SW_MAJOR_VERSION != (1U)) || (MCU_SW_MINOR_VERSION != (0U)) || (MCU_SW_PATCH_VERSION != (54U))
 #error "MCU software version in MCU.h does not match 1.0.54"
#endif
#if (MCU_VENDOR_ID !=  (11U))
 #error "MCU Vendor ID in MCU.h does not match 11"
#endif
 /* [$MCU 110] */

/*----------------------------
 * Start of code
 *----------------------------*/
#define MCU_START_SEC_CODE
#include "Mcu_MemMap.h"
/*----------------------------
 * End of code
 *----------------------------*/
#define MCU_STOP_SEC_CODE
#include "Mcu_MemMap.h"


