/** @file     Rte_Const.h
  *
  * @brief    RTA-RTE related configuration constants
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.0
  */

#ifndef RTE_CONST_H
#define RTE_CONST_H

#define RTE_CALPRM_NONE                                                       (1)
#define RTE_COMPATIBILITY_MODE                                                (1)
#define RTE_MAINFUNCTION_PERIOD_MS                                            (10)
#define RTE_MAINFUNCTION_PERIOD_NS                                            (10000000)
#define RTE_MAINFUNCTION_PERIOD_US                                            (10000)
#define RTE_MAINFUNCTION_REQUIRED                               (1)
#define RTE_MAX_USED_CORE_ID                                                  (-1)
#define RTE_MAX_USED_OSAPP_ID                                                 (0)
#define RTE_MEASUREMENT_ENABLED                                               (0)
#define RTE_NUM_TASKS                                                         (3)
#define RTE_NUM_TIMEOUT_ALARMS                                                (0)
#define RTE_OSAPI_AUTOSAR_R40                                                 (1)
#define RTE_OSCFG_AUTOSAR_R40                                                 (1)
#define RTE_PERIODIC_COUNTER_TICK_INTERVAL_US                                 (1000)
#define RTE_REQUIRES_COM                                                      (1)
#define RTE_RIPS_SUPPORT                                                      (0)
#define RTE_TASKS_ARRAYSIZE                                                   (3)
#define RTE_WOWP_EVENTS                                                       (0)
#define SCHM_GETVERSIONINFO                                                   (0)
#define SCHM_IMODEINIT                                                        (1)
#define _ParkBrake_FlatView_SwComponentTypes_ParkBrake_FlatView_CPT_BswM      SWCI7
#define _ParkBrake_FlatView_SwComponentTypes_ParkBrake_FlatView_CPT_ComM      SWCI4
#define _ParkBrake_FlatView_SwComponentTypes_ParkBrake_FlatView_CPT_ComSWC    CPT_ComSWC
#define _ParkBrake_FlatView_SwComponentTypes_ParkBrake_FlatView_CPT_EcuM      SWCI6
#define _ParkBrake_FlatView_SwComponentTypes_ParkBrake_FlatView_CPT_MemSWC    CPT_MemSWC
#define _ParkBrake_FlatView_SwComponentTypes_ParkBrake_FlatView_CPT_NvM       SWCI5
#define _ParkBrake_FlatView_SwComponentTypes_ParkBrake_FlatView_CPT_ParkSWC   CPT_ParkSWC
#define _ParkBrake_FlatView_SwComponentTypes_ParkBrake_FlatView_CPT_SystemSWC CPT_SystemSWC

#define _VCU1_FlatView_SwComponentTypes_VCU1_FlatView_CPT_ComM  CPT_ComM
#define _VCU1_FlatView_SwComponentTypes_VCU1_FlatView_DlnStMgr  DlnStMgr
#define _VCU1_FlatView_SwComponentTypes_VCU1_FlatView_DrvrItp   DrvrItp
#define _VCU1_FlatView_SwComponentTypes_VCU1_FlatView_EgyTqLimr EgyTqLimr
#define _VCU1_FlatView_SwComponentTypes_VCU1_FlatView_EmTqFil   EmTqFil
#define _VCU1_FlatView_SwComponentTypes_VCU1_FlatView_TqSplt    TqSplt
#define _VCU1_FlatView_SwComponentTypes_VCU1_FlatView_VehMtnInp VehMtnInp

/* Box: Rte: OS Environment begin */
/* The following OSENV_ macros are supported by this OS DLL: */
/* OSENV_UNSUPPORTED */
/* OSENV_RTAOS40 */
#if defined(OSENV_RTAOS40)
#if defined(OSENV_UNSUPPORTED)
#error "Please define exactly one of [ OSENV_RTAOS40, OSENV_UNSUPPORTED ] for OS_AUTOSAR40 OS API."
#endif /* defined(OSENV_UNSUPPORTED) */
#elif defined(OSENV_UNSUPPORTED)
#else
#error "Please define exactly one of [ OSENV_RTAOS40, OSENV_UNSUPPORTED ] for OS_AUTOSAR40 OS API."
#endif
/* Box: User declared atomic BSW types: begin */
/* Box: User declared atomic BSW types: end */
/* Box: Rte: OS Environment end */

#endif /* !RTE_CONST_H */
