/** @file     Rte_DlnStMgr.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.3.0 
  */

#ifndef RTE_DLNSTMGR_H
#define RTE_DLNSTMGR_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_DlnStMgr_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_DlnStMgr_10ms)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#elif defined(RTE_RUNNABLEAPI_DlnStMgr_Init)
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/


/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_DlnStMgr {
   /* Data handles */
   P2VAR(Rte_DE_uint8  , AUTOMATIC, RTE_DATA) DlnStMgr_10ms_Pp_DlnStVldty_De_DlnStVldty;
   P2VAR(Rte_DE_uint8  , AUTOMATIC, RTE_DATA) DlnStMgr_10ms_Pp_DlnSt_De_DlnSt;
   P2VAR(Rte_DE_boolean, AUTOMATIC, RTE_DATA) DlnStMgr_10ms_Pp_EmTqActv_De_EmTqActv;
   P2VAR(Rte_DE_uint8  , AUTOMATIC, RTE_DATA) DlnStMgr_10ms_Pp_ParkReq_De_ParkReq;
   P2VAR(Rte_DE_uint8  , AUTOMATIC, RTE_DATA) DlnStMgr_10ms_Rp_EpbSts_De_EpbSts;
   P2VAR(Rte_DE_uint8  , AUTOMATIC, RTE_DATA) DlnStMgr_10ms_Rp_EpbSwtSts_De_EpbSwtSts;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) DlnStMgr_10ms_Rp_JstkYpos_De_JstkYpos;
   P2VAR(Rte_DE_uint8  , AUTOMATIC, RTE_DATA) DlnStMgr_10ms_Rp_VcuWakeup_De_VcuWakeup;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) DlnStMgr_10ms_Rp_VehSpdLgt_De_VehSpdLgt;
   P2VAR(Rte_DE_uint8  , AUTOMATIC, RTE_DATA) DlnStMgr_10ms_Rp_VehSt_De_VehSt;
};
typedef struct Rte_CDS_DlnStMgr Rte_CDS_DlnStMgr;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(struct Rte_CDS_DlnStMgr, RTE_CONST) Rte_Inst_DlnStMgr;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_DlnStMgr, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE
#define RTE_START_SEC_VAR_CLEARED_32
#include "Rte_MemMap.h"
extern VAR(Rte_ImplicitBufsType, RTE_DATA) Rte_ImplicitBufs;
#define RTE_STOP_SEC_VAR_CLEARED_32
#include "Rte_MemMap.h"
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DlnStMgr_10ms)
/* Inline read optimization; Rte_IRead_DlnStMgr_10ms_Rp_EpbSts_De_EpbSts to implicit access macro */
#define Rte_IRead_DlnStMgr_10ms_Rp_EpbSts_De_EpbSts()  ( (CONST(uint8, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.rbuf7.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DlnStMgr_10ms)
/* Inline read optimization; Rte_IRead_DlnStMgr_10ms_Rp_EpbSwtSts_De_EpbSwtSts to implicit access macro */
#define Rte_IRead_DlnStMgr_10ms_Rp_EpbSwtSts_De_EpbSwtSts()  ( (CONST(uint8, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.rbuf8.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DlnStMgr_10ms)
/* Inline read optimization; Rte_IRead_DlnStMgr_10ms_Rp_JstkYpos_De_JstkYpos to implicit access macro */
#define Rte_IRead_DlnStMgr_10ms_Rp_JstkYpos_De_JstkYpos()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf26.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DlnStMgr_10ms)
/* Inline read optimization; Rte_IRead_DlnStMgr_10ms_Rp_VcuWakeup_De_VcuWakeup to implicit access macro */
#define Rte_IRead_DlnStMgr_10ms_Rp_VcuWakeup_De_VcuWakeup()  ( (CONST(uint8, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.rbuf9.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DlnStMgr_10ms)
/* Inline read optimization; Rte_IRead_DlnStMgr_10ms_Rp_VehSpdLgt_De_VehSpdLgt to implicit access macro */
#define Rte_IRead_DlnStMgr_10ms_Rp_VehSpdLgt_De_VehSpdLgt()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf22.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DlnStMgr_10ms)
/* Inline read optimization; Rte_IRead_DlnStMgr_10ms_Rp_VehSt_De_VehSt to implicit access macro */
#define Rte_IRead_DlnStMgr_10ms_Rp_VehSt_De_VehSt()  ( (CONST(uint8, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.rbuf6.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DlnStMgr_10ms)
/* Inline write optimization; Rte_IWriteRef_DlnStMgr_10ms_Pp_DlnStVldty_De_DlnStVldty to implicit access macro */
#define Rte_IWriteRef_DlnStMgr_10ms_Pp_DlnStVldty_De_DlnStVldty()  ( (P2VAR(uint8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf29.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DlnStMgr_10ms)
/* Inline write optimization; Rte_IWriteRef_DlnStMgr_10ms_Pp_DlnSt_De_DlnSt to implicit access macro */
#define Rte_IWriteRef_DlnStMgr_10ms_Pp_DlnSt_De_DlnSt()  ( (P2VAR(uint8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf28.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DlnStMgr_10ms)
/* Inline write optimization; Rte_IWriteRef_DlnStMgr_10ms_Pp_EmTqActv_De_EmTqActv to implicit access macro */
#define Rte_IWriteRef_DlnStMgr_10ms_Pp_EmTqActv_De_EmTqActv()  ( (P2VAR(boolean, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf19.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DlnStMgr_10ms)
/* Inline write optimization; Rte_IWriteRef_DlnStMgr_10ms_Pp_ParkReq_De_ParkReq to implicit access macro */
#define Rte_IWriteRef_DlnStMgr_10ms_Pp_ParkReq_De_ParkReq()  ( (P2VAR(uint8, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf27.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DlnStMgr_10ms)
/* Inline write optimization; Rte_IWrite_DlnStMgr_10ms_Pp_DlnStVldty_De_DlnStVldty to implicit access macro */
#define Rte_IWrite_DlnStMgr_10ms_Pp_DlnStVldty_De_DlnStVldty( data )  ( Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf29.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DlnStMgr_10ms)
/* Inline write optimization; Rte_IWrite_DlnStMgr_10ms_Pp_DlnSt_De_DlnSt to implicit access macro */
#define Rte_IWrite_DlnStMgr_10ms_Pp_DlnSt_De_DlnSt( data )  ( Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf28.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DlnStMgr_10ms)
/* Inline write optimization; Rte_IWrite_DlnStMgr_10ms_Pp_EmTqActv_De_EmTqActv to implicit access macro */
#define Rte_IWrite_DlnStMgr_10ms_Pp_EmTqActv_De_EmTqActv( data )  ( Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf19.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DlnStMgr_10ms)
/* Inline write optimization; Rte_IWrite_DlnStMgr_10ms_Pp_ParkReq_De_ParkReq to implicit access macro */
#define Rte_IWrite_DlnStMgr_10ms_Pp_ParkReq_De_ParkReq( data )  ( Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf27.value = (data) )
#endif

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define DlnStMgr_START_SEC_QmCode
#include "DlnStMgr_MemMap.h"
FUNC(void, DlnStMgr_QmCode) DlnStMgr_10ms(void);
FUNC(void, DlnStMgr_QmCode) DlnStMgr_Init(void);
#define DlnStMgr_STOP_SEC_QmCode
#include "DlnStMgr_MemMap.h"

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_DLNSTMGR_H */
