/** @file     Rte_EgyTqLimr.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.3.0 
  */

#ifndef RTE_EGYTQLIMR_H
#define RTE_EGYTQLIMR_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_EgyTqLimr_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_EgyTqLimr_10ms)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#elif defined(RTE_RUNNABLEAPI_EgyTqLimr_Init)
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/


/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_EgyTqLimr {
   /* Data handles */
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) EgyTqLimr_10ms_Pp_EmTqNegLimShoTerm_De_EmTqNegLimShoTerm;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) EgyTqLimr_10ms_Pp_EmTqPosLimShoTerm_De_EmTqPosLimShoTerm;
   P2VAR(Rte_DE_uint8  , AUTOMATIC, RTE_DATA) EgyTqLimr_10ms_Rp_DlnSt_De_DlnSt;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) EgyTqLimr_10ms_Rp_EmNFild_De_EmNFild;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) EgyTqLimr_10ms_Rp_EmTqReLeNegLim_De_EmTqReLeNegLim;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) EgyTqLimr_10ms_Rp_EmTqReLePosLim_De_EmTqReLePosLim;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) EgyTqLimr_10ms_Rp_EmTqReRiNegLim_De_EmTqReRiNegLim;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) EgyTqLimr_10ms_Rp_EmTqReRiPosLim_De_EmTqReRiPosLim;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) EgyTqLimr_10ms_Rp_HvBattVltg_De_HvBattVltg;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) EgyTqLimr_10ms_Rp_InvCurrTotAllwdMax_De_InvCurrTotAllwdMax;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) EgyTqLimr_10ms_Rp_InvCurrTotAllwdMin_De_InvCurrTotAllwdMin;
};
typedef struct Rte_CDS_EgyTqLimr Rte_CDS_EgyTqLimr;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(struct Rte_CDS_EgyTqLimr, RTE_CONST) Rte_Inst_EgyTqLimr;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_EgyTqLimr, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE
#define RTE_START_SEC_VAR_CLEARED_32
#include "Rte_MemMap.h"
extern VAR(Rte_ImplicitBufsType, RTE_DATA) Rte_ImplicitBufs;
#define RTE_STOP_SEC_VAR_CLEARED_32
#include "Rte_MemMap.h"
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EgyTqLimr_10ms)
/* Inline read optimization; Rte_IRead_EgyTqLimr_10ms_Rp_DlnSt_De_DlnSt to implicit access macro */
#define Rte_IRead_EgyTqLimr_10ms_Rp_DlnSt_De_DlnSt()  ( (CONST(uint8, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf28.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EgyTqLimr_10ms)
/* Inline read optimization; Rte_IRead_EgyTqLimr_10ms_Rp_EmNFild_De_EmNFild to implicit access macro */
#define Rte_IRead_EgyTqLimr_10ms_Rp_EmNFild_De_EmNFild()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf23.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EgyTqLimr_10ms)
/* Inline read optimization; Rte_IRead_EgyTqLimr_10ms_Rp_EmTqReLeNegLim_De_EmTqReLeNegLim to implicit access macro */
#define Rte_IRead_EgyTqLimr_10ms_Rp_EmTqReLeNegLim_De_EmTqReLeNegLim()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.rbuf13.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EgyTqLimr_10ms)
/* Inline read optimization; Rte_IRead_EgyTqLimr_10ms_Rp_EmTqReLePosLim_De_EmTqReLePosLim to implicit access macro */
#define Rte_IRead_EgyTqLimr_10ms_Rp_EmTqReLePosLim_De_EmTqReLePosLim()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.rbuf10.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EgyTqLimr_10ms)
/* Inline read optimization; Rte_IRead_EgyTqLimr_10ms_Rp_EmTqReRiNegLim_De_EmTqReRiNegLim to implicit access macro */
#define Rte_IRead_EgyTqLimr_10ms_Rp_EmTqReRiNegLim_De_EmTqReRiNegLim()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.rbuf14.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EgyTqLimr_10ms)
/* Inline read optimization; Rte_IRead_EgyTqLimr_10ms_Rp_EmTqReRiPosLim_De_EmTqReRiPosLim to implicit access macro */
#define Rte_IRead_EgyTqLimr_10ms_Rp_EmTqReRiPosLim_De_EmTqReRiPosLim()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.rbuf11.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EgyTqLimr_10ms)
/* Inline read optimization; Rte_IRead_EgyTqLimr_10ms_Rp_HvBattVltg_De_HvBattVltg to implicit access macro */
#define Rte_IRead_EgyTqLimr_10ms_Rp_HvBattVltg_De_HvBattVltg()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.rbuf12.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EgyTqLimr_10ms)
/* Inline read optimization; Rte_IRead_EgyTqLimr_10ms_Rp_InvCurrTotAllwdMax_De_InvCurrTotAllwdMax to implicit access macro */
#define Rte_IRead_EgyTqLimr_10ms_Rp_InvCurrTotAllwdMax_De_InvCurrTotAllwdMax()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf24.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EgyTqLimr_10ms)
/* Inline read optimization; Rte_IRead_EgyTqLimr_10ms_Rp_InvCurrTotAllwdMin_De_InvCurrTotAllwdMin to implicit access macro */
#define Rte_IRead_EgyTqLimr_10ms_Rp_InvCurrTotAllwdMin_De_InvCurrTotAllwdMin()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf25.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EgyTqLimr_10ms)
/* Inline write optimization; Rte_IWriteRef_EgyTqLimr_10ms_Pp_EmTqNegLimShoTerm_De_EmTqNegLimShoTerm to implicit access macro */
#define Rte_IWriteRef_EgyTqLimr_10ms_Pp_EmTqNegLimShoTerm_De_EmTqNegLimShoTerm()  ( (P2VAR(float32, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf21.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EgyTqLimr_10ms)
/* Inline write optimization; Rte_IWriteRef_EgyTqLimr_10ms_Pp_EmTqPosLimShoTerm_De_EmTqPosLimShoTerm to implicit access macro */
#define Rte_IWriteRef_EgyTqLimr_10ms_Pp_EmTqPosLimShoTerm_De_EmTqPosLimShoTerm()  ( (P2VAR(float32, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf20.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EgyTqLimr_10ms)
/* Inline write optimization; Rte_IWrite_EgyTqLimr_10ms_Pp_EmTqNegLimShoTerm_De_EmTqNegLimShoTerm to implicit access macro */
#define Rte_IWrite_EgyTqLimr_10ms_Pp_EmTqNegLimShoTerm_De_EmTqNegLimShoTerm( data )  ( Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf21.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EgyTqLimr_10ms)
/* Inline write optimization; Rte_IWrite_EgyTqLimr_10ms_Pp_EmTqPosLimShoTerm_De_EmTqPosLimShoTerm to implicit access macro */
#define Rte_IWrite_EgyTqLimr_10ms_Pp_EmTqPosLimShoTerm_De_EmTqPosLimShoTerm( data )  ( Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf20.value = (data) )
#endif

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define EgyTqLimr_START_SEC_QmCode
#include "EgyTqLimr_MemMap.h"
FUNC(void, EgyTqLimr_QmCode) EgyTqLimr_10ms(void);
FUNC(void, EgyTqLimr_QmCode) EgyTqLimr_Init(void);
#define EgyTqLimr_STOP_SEC_QmCode
#include "EgyTqLimr_MemMap.h"

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_EGYTQLIMR_H */
