/** @file     Rte_DataHandleType.h
  *
  * @brief    RTE DataElement type definitions
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.0
  */

#ifndef RTE_DATA_HANDLE_TYPE_H
#define RTE_DATA_HANDLE_TYPE_H

#include "Rte_Type.h"
#include "Rte_Cfg.h"

typedef struct {
   boolean value;
} Rte_DE_boolean;

typedef struct {
   float32 value;
} Rte_DE_float32;

typedef struct {
   uint8 value;
} Rte_DE_uint8;

typedef struct {
   Rte_DE_float32 rbuf0;
   Rte_DE_float32 rbuf1;
   Rte_DE_float32 rbuf10;
   Rte_DE_float32 rbuf11;
   Rte_DE_float32 rbuf12;
   Rte_DE_float32 rbuf13;
   Rte_DE_float32 rbuf14;
   Rte_DE_float32 rbuf2;
   Rte_DE_float32 rbuf3;
   Rte_DE_float32 rbuf4;
   Rte_DE_float32 rbuf5;
   Rte_DE_uint8   rbuf6;
   Rte_DE_uint8   rbuf7;
   Rte_DE_uint8   rbuf8;
   Rte_DE_uint8   rbuf9;
   Rte_DE_float32 sbuf15;
   Rte_DE_float32 sbuf16;
   Rte_DE_boolean sbuf17;
   Rte_DE_float32 sbuf18;
   Rte_DE_boolean sbuf19;
   Rte_DE_float32 sbuf20;
   Rte_DE_float32 sbuf21;
   Rte_DE_float32 sbuf22;
   Rte_DE_float32 sbuf23;
   Rte_DE_float32 sbuf24;
   Rte_DE_float32 sbuf25;
   Rte_DE_float32 sbuf26;
   Rte_DE_uint8   sbuf27;
   Rte_DE_uint8   sbuf28;
   Rte_DE_uint8   sbuf29;
   Rte_DE_float32 sbuf30;
   Rte_DE_float32 sbuf31;
   Rte_DE_boolean sbuf32;
} Rte_TDB_OsTask_ASW_PeriodicEvents;

typedef union {
   Rte_TDB_OsTask_ASW_PeriodicEvents Rte_OsTask_ASW_PeriodicEvents;
} Rte_ISA_1;

typedef struct {
   Rte_ISA_1 isa_1;
} Rte_ImplicitBufsType;


#endif /* !RTE_DATA_HANDLE_TYPE_H */
