/** @file     Rte_DlnStMgr_Type.h
  *
  * @brief    Application types header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.3.0 
  */

#ifndef RTE_DlnStMgr_TYPE_H
#define RTE_DlnStMgr_TYPE_H

#include "Rte_Type.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* BEGIN: SWC specific types */
/* END: SWC specific types */

/* BEGIN: SWC specific definitions */
#if !defined(RTE_CORE)

/* Box: /VCU_Software_pkg/software_config/DataTypes/ApplicationDataTypes/DlnStEnum begin */
/* Box: "DlnSt_Park" begin */
#ifndef DlnSt_Park
#define DlnSt_Park (0U)
#endif /* !DlnSt_Park */
/* Box: "DlnSt_Park" end */
/* Box: "DlnSt_Rvs" begin */
#ifndef DlnSt_Rvs
#define DlnSt_Rvs (1U)
#endif /* !DlnSt_Rvs */
/* Box: "DlnSt_Rvs" end */
/* Box: "DlnSt_Neut" begin */
#ifndef DlnSt_Neut
#define DlnSt_Neut (2U)
#endif /* !DlnSt_Neut */
/* Box: "DlnSt_Neut" end */
/* Box: "DlnSt_Drv" begin */
#ifndef DlnSt_Drv
#define DlnSt_Drv (3U)
#endif /* !DlnSt_Drv */
/* Box: "DlnSt_Drv" end */
/* Box: /VCU_Software_pkg/software_config/DataTypes/ApplicationDataTypes/DlnStEnum end */

/* Box: /VCU_Software_pkg/software_config/DataTypes/ApplicationDataTypes/DlnStVldtyEnum begin */
/* Box: "DlnStVldty_Vld" begin */
#ifndef DlnStVldty_Vld
#define DlnStVldty_Vld (0U)
#endif /* !DlnStVldty_Vld */
/* Box: "DlnStVldty_Vld" end */
/* Box: "DlnStVldty_Invld" begin */
#ifndef DlnStVldty_Invld
#define DlnStVldty_Invld (1U)
#endif /* !DlnStVldty_Invld */
/* Box: "DlnStVldty_Invld" end */
/* Box: /VCU_Software_pkg/software_config/DataTypes/ApplicationDataTypes/DlnStVldtyEnum end */

/* Box: /VCU_Software_pkg/software_config/DataTypes/ApplicationDataTypes/EpbStsEnum begin */
/* Box: "EpbSts_Stb" begin */
#ifndef EpbSts_Stb
#define EpbSts_Stb (0U)
#endif /* !EpbSts_Stb */
/* Box: "EpbSts_Stb" end */
/* Box: "EpbSts_Appld" begin */
#ifndef EpbSts_Appld
#define EpbSts_Appld (1U)
#endif /* !EpbSts_Appld */
/* Box: "EpbSts_Appld" end */
/* Box: "EpbSts_Reld" begin */
#ifndef EpbSts_Reld
#define EpbSts_Reld (2U)
#endif /* !EpbSts_Reld */
/* Box: "EpbSts_Reld" end */
/* Box: "EpbSts_Applng" begin */
#ifndef EpbSts_Applng
#define EpbSts_Applng (3U)
#endif /* !EpbSts_Applng */
/* Box: "EpbSts_Applng" end */
/* Box: "EpbSts_Relsng" begin */
#ifndef EpbSts_Relsng
#define EpbSts_Relsng (4U)
#endif /* !EpbSts_Relsng */
/* Box: "EpbSts_Relsng" end */
/* Box: "EpbSts_Flt" begin */
#ifndef EpbSts_Flt
#define EpbSts_Flt (5U)
#endif /* !EpbSts_Flt */
/* Box: "EpbSts_Flt" end */
/* Box: "EpbSts_Resd6" begin */
#ifndef EpbSts_Resd6
#define EpbSts_Resd6 (6U)
#endif /* !EpbSts_Resd6 */
/* Box: "EpbSts_Resd6" end */
/* Box: "EpbSts_Resd7" begin */
#ifndef EpbSts_Resd7
#define EpbSts_Resd7 (7U)
#endif /* !EpbSts_Resd7 */
/* Box: "EpbSts_Resd7" end */
/* Box: /VCU_Software_pkg/software_config/DataTypes/ApplicationDataTypes/EpbStsEnum end */

/* Box: /VCU_Software_pkg/software_config/DataTypes/ApplicationDataTypes/EpbSwtStsEnum begin */
/* Box: "EpbSwtSts_SwtNotPsd" begin */
#ifndef EpbSwtSts_SwtNotPsd
#define EpbSwtSts_SwtNotPsd (0U)
#endif /* !EpbSwtSts_SwtNotPsd */
/* Box: "EpbSwtSts_SwtNotPsd" end */
/* Box: "EpbSwtSts_SwtPsd" begin */
#ifndef EpbSwtSts_SwtPsd
#define EpbSwtSts_SwtPsd (1U)
#endif /* !EpbSwtSts_SwtPsd */
/* Box: "EpbSwtSts_SwtPsd" end */
/* Box: /VCU_Software_pkg/software_config/DataTypes/ApplicationDataTypes/EpbSwtStsEnum end */

/* Box: /VCU_Software_pkg/software_config/DataTypes/ApplicationDataTypes/ParkReqEnum begin */
/* Box: "ParkReq_Apply" begin */
#ifndef ParkReq_Apply
#define ParkReq_Apply (0U)
#endif /* !ParkReq_Apply */
/* Box: "ParkReq_Apply" end */
/* Box: "ParkReq_Rels" begin */
#ifndef ParkReq_Rels
#define ParkReq_Rels (1U)
#endif /* !ParkReq_Rels */
/* Box: "ParkReq_Rels" end */
/* Box: "ParkReq_NoReq" begin */
#ifndef ParkReq_NoReq
#define ParkReq_NoReq (2U)
#endif /* !ParkReq_NoReq */
/* Box: "ParkReq_NoReq" end */
/* Box: /VCU_Software_pkg/software_config/DataTypes/ApplicationDataTypes/ParkReqEnum end */

/* Box: /VCU_Software_pkg/software_config/DataTypes/ApplicationDataTypes/VcuWakeupEnum begin */
/* Box: "VcuWakeup_Off" begin */
#ifndef VcuWakeup_Off
#define VcuWakeup_Off (0U)
#endif /* !VcuWakeup_Off */
/* Box: "VcuWakeup_Off" end */
/* Box: "VcuWakeup_On" begin */
#ifndef VcuWakeup_On
#define VcuWakeup_On (1U)
#endif /* !VcuWakeup_On */
/* Box: "VcuWakeup_On" end */
/* Box: "VcuWakeup_Drv" begin */
#ifndef VcuWakeup_Drv
#define VcuWakeup_Drv (2U)
#endif /* !VcuWakeup_Drv */
/* Box: "VcuWakeup_Drv" end */
/* Box: "VcuWakeup_Resd3" begin */
#ifndef VcuWakeup_Resd3
#define VcuWakeup_Resd3 (3U)
#endif /* !VcuWakeup_Resd3 */
/* Box: "VcuWakeup_Resd3" end */
/* Box: /VCU_Software_pkg/software_config/DataTypes/ApplicationDataTypes/VcuWakeupEnum end */

/* Box: /VCU_Software_pkg/software_config/DataTypes/ApplicationDataTypes/VehStEnum begin */
/* Box: "VehSt_VehShutdn" begin */
#ifndef VehSt_VehShutdn
#define VehSt_VehShutdn (0U)
#endif /* !VehSt_VehShutdn */
/* Box: "VehSt_VehShutdn" end */
/* Box: "VehSt_VehStrtUp" begin */
#ifndef VehSt_VehStrtUp
#define VehSt_VehStrtUp (1U)
#endif /* !VehSt_VehStrtUp */
/* Box: "VehSt_VehStrtUp" end */
/* Box: "VehSt_SafeToEntrExit" begin */
#ifndef VehSt_SafeToEntrExit
#define VehSt_SafeToEntrExit (2U)
#endif /* !VehSt_SafeToEntrExit */
/* Box: "VehSt_SafeToEntrExit" end */
/* Box: "VehSt_SafeToDrv" begin */
#ifndef VehSt_SafeToDrv
#define VehSt_SafeToDrv (3U)
#endif /* !VehSt_SafeToDrv */
/* Box: "VehSt_SafeToDrv" end */
/* Box: "VehSt_PrepToAd" begin */
#ifndef VehSt_PrepToAd
#define VehSt_PrepToAd (4U)
#endif /* !VehSt_PrepToAd */
/* Box: "VehSt_PrepToAd" end */
/* Box: "VehSt_Ad" begin */
#ifndef VehSt_Ad
#define VehSt_Ad (5U)
#endif /* !VehSt_Ad */
/* Box: "VehSt_Ad" end */
/* Box: "VehSt_ChrgrCnctd" begin */
#ifndef VehSt_ChrgrCnctd
#define VehSt_ChrgrCnctd (6U)
#endif /* !VehSt_ChrgrCnctd */
/* Box: "VehSt_ChrgrCnctd" end */
/* Box: "VehSt_Resd7" begin */
#ifndef VehSt_Resd7
#define VehSt_Resd7 (7U)
#endif /* !VehSt_Resd7 */
/* Box: "VehSt_Resd7" end */
/* Box: "VehSt_DrvgMan" begin */
#ifndef VehSt_DrvgMan
#define VehSt_DrvgMan (8U)
#endif /* !VehSt_DrvgMan */
/* Box: "VehSt_DrvgMan" end */
/* Box: "VehSt_Chrgng" begin */
#ifndef VehSt_Chrgng
#define VehSt_Chrgng (9U)
#endif /* !VehSt_Chrgng */
/* Box: "VehSt_Chrgng" end */
/* Box: "VehSt_VehShutdnCmpl" begin */
#ifndef VehSt_VehShutdnCmpl
#define VehSt_VehShutdnCmpl (10U)
#endif /* !VehSt_VehShutdnCmpl */
/* Box: "VehSt_VehShutdnCmpl" end */
/* Box: "VehSt_InitiateVehSecrMod" begin */
#ifndef VehSt_InitiateVehSecrMod
#define VehSt_InitiateVehSecrMod (11U)
#endif /* !VehSt_InitiateVehSecrMod */
/* Box: "VehSt_InitiateVehSecrMod" end */
/* Box: "VehSt_SecrModSafeSt" begin */
#ifndef VehSt_SecrModSafeSt
#define VehSt_SecrModSafeSt (12U)
#endif /* !VehSt_SecrModSafeSt */
/* Box: "VehSt_SecrModSafeSt" end */
/* Box: "VehSt_Resd13" begin */
#ifndef VehSt_Resd13
#define VehSt_Resd13 (13U)
#endif /* !VehSt_Resd13 */
/* Box: "VehSt_Resd13" end */
/* Box: "VehSt_Resd14" begin */
#ifndef VehSt_Resd14
#define VehSt_Resd14 (14U)
#endif /* !VehSt_Resd14 */
/* Box: "VehSt_Resd14" end */
/* Box: "VehSt_Resd15" begin */
#ifndef VehSt_Resd15
#define VehSt_Resd15 (15U)
#endif /* !VehSt_Resd15 */
/* Box: "VehSt_Resd15" end */
/* Box: /VCU_Software_pkg/software_config/DataTypes/ApplicationDataTypes/VehStEnum end */

/* Box: /VCU_Software_pkg/software_config/DataTypes/ImplementationDataTypes/boolean begin */
/* Box: "FALSE" begin */
#ifndef FALSE
#define FALSE (0U)
#endif /* !FALSE */
/* Box: "FALSE" end */
/* Box: "TRUE" begin */
#ifndef TRUE
#define TRUE (1U)
#endif /* !TRUE */
/* Box: "TRUE" end */
/* Box: /VCU_Software_pkg/software_config/DataTypes/ImplementationDataTypes/boolean end */
#endif /* !defined(RTE_CORE) */
/* END: SWC specific definitions */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_DlnStMgr_TYPE_H */
