/** @file     Rte_BswM_Type.h
  *
  * @brief    Application types header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.0
  */

#ifndef RTE_BswM_TYPE_H
#define RTE_BswM_TYPE_H

#include "Rte_Type.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* BEGIN: SWC specific types */
#ifndef RTE_CORE
#ifndef RTE_MODETYPE_MDG_SHUTDOWN
#define RTE_MODETYPE_MDG_SHUTDOWN

typedef uint8 Rte_ModeType_MDG_ShutDown;

#endif /* !RTE_MODETYPE_MDG_SHUTDOWN */
#endif /* RTE_CORE */

/* END: SWC specific types */

/* BEGIN: SWC specific definitions */
#ifndef RTE_CORE
#ifndef RTE_MODE_MDG_ShutDown_RUN
#define RTE_MODE_MDG_ShutDown_RUN                1U
#endif /* !RTE_MODE_MDG_ShutDown_RUN */
#ifndef RTE_MODE_MDG_ShutDown_SHUT_DOWN
#define RTE_MODE_MDG_ShutDown_SHUT_DOWN          0U
#endif /* !RTE_MODE_MDG_ShutDown_SHUT_DOWN */
#ifndef RTE_TRANSITION_MDG_ShutDown
#define RTE_TRANSITION_MDG_ShutDown              2U
#endif /* !RTE_TRANSITION_MDG_ShutDown */
#endif /* RTE_CORE */

/* END: SWC specific definitions */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_BswM_TYPE_H */
