/** @file     Rte_ComSWC.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.0
  */

#ifndef RTE_COMSWC_H
#define RTE_COMSWC_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_ComSWC_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_RE_ComSWC_main_10ms)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/


/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_ComSWC {
   uint8 Rte_Dummy;
};
typedef struct Rte_CDS_ComSWC Rte_CDS_ComSWC;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(struct Rte_CDS_ComSWC, RTE_CONST) Rte_Inst_ComSWC;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_ComSWC, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE

#define RTE_COMSWC_START_SEC_CODE
#include "Rte_MemMap.h"
FUNC(Std_ReturnType, RTE_CODE) Rte_Write_ComSWC_PP_ParkControl_DE_ParkState(VAR(boolean, AUTOMATIC) data);
FUNC(Std_ReturnType, RTE_CODE) Rte_Write_ComSWC_PP_comParkStatus_DE_ParkState(VAR(boolean, AUTOMATIC) data);
#define RTE_COMSWC_STOP_SEC_CODE
#include "Rte_MemMap.h"
#define RTE_START_SEC_VAR_CLEARED_BOOLEAN
#include "Rte_MemMap.h"
extern VAR(boolean, RTE_DATA) Rte_Rx_000000;
#define RTE_STOP_SEC_VAR_CLEARED_BOOLEAN
#include "Rte_MemMap.h"
#define RTE_START_SEC_VAR_CLEARED_BOOLEAN
#include "Rte_MemMap.h"
extern VAR(boolean, RTE_DATA) Rte_Rx_000002;
#define RTE_STOP_SEC_VAR_CLEARED_BOOLEAN
#include "Rte_MemMap.h"
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_RE_ComSWC_main_10ms)
/* Inline read optimization; Rte_Read_RP_ParkStatus_DE_ParkState to direct access */
#define Rte_Read_RP_ParkStatus_DE_ParkState( data )  ( RTE_ATOMIC8((*(data)) = Rte_Rx_000002),((VAR(Std_ReturnType, AUTOMATIC))RTE_E_OK) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_RE_ComSWC_main_10ms)
/* Inline read optimization; Rte_Read_RP_comParkControl_DE_ParkState to direct access */
#define Rte_Read_RP_comParkControl_DE_ParkState( data )  ( ((*(data)) = Rte_Rx_000000),((VAR(Std_ReturnType, AUTOMATIC))RTE_E_OK) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_RE_ComSWC_main_10ms)
#define Rte_Write_PP_ParkControl_DE_ParkState( data ) (Rte_Write_ComSWC_PP_ParkControl_DE_ParkState(data))
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_RE_ComSWC_main_10ms)
#define Rte_Write_PP_comParkStatus_DE_ParkState( data ) (Rte_Write_ComSWC_PP_comParkStatus_DE_ParkState(data))
#endif

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define ComSWC_START_SEC_CODE
#include "ComSWC_MemMap.h"
FUNC(void, ComSWC_CODE) RE_ComSWC_main_10ms(void);
#define ComSWC_STOP_SEC_CODE
#include "ComSWC_MemMap.h"

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_COMSWC_H */
