/** @file     Rte_VehMtnInp.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.3.0 
  */

#ifndef RTE_VEHMTNINP_H
#define RTE_VEHMTNINP_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_VehMtnInp_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_VehMtnInp_10ms)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#elif defined(RTE_RUNNABLEAPI_VehMtnInp_Init)
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/


/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_VehMtnInp {
   /* Data handles */
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) VehMtnInp_10ms_Pp_EmNFild_De_EmNFild;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) VehMtnInp_10ms_Pp_InvCurrTotAllwdMax_De_InvCurrTotAllwdMax;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) VehMtnInp_10ms_Pp_InvCurrTotAllwdMin_De_InvCurrTotAllwdMin;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) VehMtnInp_10ms_Pp_JstkYpos_De_JstkYpos;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) VehMtnInp_10ms_Pp_VehSpdLgt_De_VehSpdLgt;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) VehMtnInp_10ms_Rp_BrkData_De_BrkData;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) VehMtnInp_10ms_Rp_CurrMaxAllwdDcha_De_CurrMaxAllwdDcha;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) VehMtnInp_10ms_Rp_CurrMaxAllwdRgn_De_CurrMaxAllwdRgn;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) VehMtnInp_10ms_Rp_EmNEstimReLe_De_EmNEstimReLe;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) VehMtnInp_10ms_Rp_EmNEstimReRi_De_EmNEstimReRi;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) VehMtnInp_10ms_Rp_ThrData_De_ThrData;
};
typedef struct Rte_CDS_VehMtnInp Rte_CDS_VehMtnInp;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(struct Rte_CDS_VehMtnInp, RTE_CONST) Rte_Inst_VehMtnInp;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_VehMtnInp, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE
#define RTE_START_SEC_VAR_CLEARED_32
#include "Rte_MemMap.h"
extern VAR(Rte_ImplicitBufsType, RTE_DATA) Rte_ImplicitBufs;
#define RTE_STOP_SEC_VAR_CLEARED_32
#include "Rte_MemMap.h"
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_VehMtnInp_10ms)
/* Inline read optimization; Rte_IRead_VehMtnInp_10ms_Rp_BrkData_De_BrkData to implicit access macro */
#define Rte_IRead_VehMtnInp_10ms_Rp_BrkData_De_BrkData()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.rbuf0.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_VehMtnInp_10ms)
/* Inline read optimization; Rte_IRead_VehMtnInp_10ms_Rp_CurrMaxAllwdDcha_De_CurrMaxAllwdDcha to implicit access macro */
#define Rte_IRead_VehMtnInp_10ms_Rp_CurrMaxAllwdDcha_De_CurrMaxAllwdDcha()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.rbuf1.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_VehMtnInp_10ms)
/* Inline read optimization; Rte_IRead_VehMtnInp_10ms_Rp_CurrMaxAllwdRgn_De_CurrMaxAllwdRgn to implicit access macro */
#define Rte_IRead_VehMtnInp_10ms_Rp_CurrMaxAllwdRgn_De_CurrMaxAllwdRgn()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.rbuf2.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_VehMtnInp_10ms)
/* Inline read optimization; Rte_IRead_VehMtnInp_10ms_Rp_EmNEstimReLe_De_EmNEstimReLe to implicit access macro */
#define Rte_IRead_VehMtnInp_10ms_Rp_EmNEstimReLe_De_EmNEstimReLe()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.rbuf3.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_VehMtnInp_10ms)
/* Inline read optimization; Rte_IRead_VehMtnInp_10ms_Rp_EmNEstimReRi_De_EmNEstimReRi to implicit access macro */
#define Rte_IRead_VehMtnInp_10ms_Rp_EmNEstimReRi_De_EmNEstimReRi()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.rbuf4.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_VehMtnInp_10ms)
/* Inline read optimization; Rte_IRead_VehMtnInp_10ms_Rp_ThrData_De_ThrData to implicit access macro */
#define Rte_IRead_VehMtnInp_10ms_Rp_ThrData_De_ThrData()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.rbuf5.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_VehMtnInp_10ms)
/* Inline write optimization; Rte_IWriteRef_VehMtnInp_10ms_Pp_EmNFild_De_EmNFild to implicit access macro */
#define Rte_IWriteRef_VehMtnInp_10ms_Pp_EmNFild_De_EmNFild()  ( (P2VAR(float32, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf23.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_VehMtnInp_10ms)
/* Inline write optimization; Rte_IWriteRef_VehMtnInp_10ms_Pp_InvCurrTotAllwdMax_De_InvCurrTotAllwdMax to implicit access macro */
#define Rte_IWriteRef_VehMtnInp_10ms_Pp_InvCurrTotAllwdMax_De_InvCurrTotAllwdMax()  ( (P2VAR(float32, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf24.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_VehMtnInp_10ms)
/* Inline write optimization; Rte_IWriteRef_VehMtnInp_10ms_Pp_InvCurrTotAllwdMin_De_InvCurrTotAllwdMin to implicit access macro */
#define Rte_IWriteRef_VehMtnInp_10ms_Pp_InvCurrTotAllwdMin_De_InvCurrTotAllwdMin()  ( (P2VAR(float32, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf25.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_VehMtnInp_10ms)
/* Inline write optimization; Rte_IWriteRef_VehMtnInp_10ms_Pp_JstkYpos_De_JstkYpos to implicit access macro */
#define Rte_IWriteRef_VehMtnInp_10ms_Pp_JstkYpos_De_JstkYpos()  ( (P2VAR(float32, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf26.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_VehMtnInp_10ms)
/* Inline write optimization; Rte_IWriteRef_VehMtnInp_10ms_Pp_VehSpdLgt_De_VehSpdLgt to implicit access macro */
#define Rte_IWriteRef_VehMtnInp_10ms_Pp_VehSpdLgt_De_VehSpdLgt()  ( (P2VAR(float32, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf22.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_VehMtnInp_10ms)
/* Inline write optimization; Rte_IWrite_VehMtnInp_10ms_Pp_EmNFild_De_EmNFild to implicit access macro */
#define Rte_IWrite_VehMtnInp_10ms_Pp_EmNFild_De_EmNFild( data )  ( Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf23.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_VehMtnInp_10ms)
/* Inline write optimization; Rte_IWrite_VehMtnInp_10ms_Pp_InvCurrTotAllwdMax_De_InvCurrTotAllwdMax to implicit access macro */
#define Rte_IWrite_VehMtnInp_10ms_Pp_InvCurrTotAllwdMax_De_InvCurrTotAllwdMax( data )  ( Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf24.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_VehMtnInp_10ms)
/* Inline write optimization; Rte_IWrite_VehMtnInp_10ms_Pp_InvCurrTotAllwdMin_De_InvCurrTotAllwdMin to implicit access macro */
#define Rte_IWrite_VehMtnInp_10ms_Pp_InvCurrTotAllwdMin_De_InvCurrTotAllwdMin( data )  ( Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf25.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_VehMtnInp_10ms)
/* Inline write optimization; Rte_IWrite_VehMtnInp_10ms_Pp_JstkYpos_De_JstkYpos to implicit access macro */
#define Rte_IWrite_VehMtnInp_10ms_Pp_JstkYpos_De_JstkYpos( data )  ( Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf26.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_VehMtnInp_10ms)
/* Inline write optimization; Rte_IWrite_VehMtnInp_10ms_Pp_VehSpdLgt_De_VehSpdLgt to implicit access macro */
#define Rte_IWrite_VehMtnInp_10ms_Pp_VehSpdLgt_De_VehSpdLgt( data )  ( Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf22.value = (data) )
#endif

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define VehMtnInp_START_SEC_QmCode
#include "VehMtnInp_MemMap.h"
FUNC(void, VehMtnInp_QmCode) VehMtnInp_VehMtnInp_10ms(void);
FUNC(void, VehMtnInp_QmCode) VehMtnInp_VehMtnInp_Init(void);
#define VehMtnInp_STOP_SEC_QmCode
#include "VehMtnInp_MemMap.h"

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_VEHMTNINP_H */
