/** @file     Rte_TqSplt.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.3.0 
  */

#ifndef RTE_TQSPLT_H
#define RTE_TQSPLT_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_TqSplt_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_TqSplt_10ms)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#elif defined(RTE_RUNNABLEAPI_TqSplt_Init)
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/


/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_TqSplt {
   /* Data handles */
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) TqSplt_10ms_Pp_EmTqReqLimd_De_EmTqReqLimd;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) TqSplt_10ms_Pp_FoudnBrkTqReq_De_FoudnBrkTqReq;
   P2VAR(Rte_DE_boolean, AUTOMATIC, RTE_DATA) TqSplt_10ms_Rp_BrkReqd_De_BrkReqd;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) TqSplt_10ms_Rp_DrvrTqReq_De_DrvrTqReq;
   P2VAR(Rte_DE_boolean, AUTOMATIC, RTE_DATA) TqSplt_10ms_Rp_EmTqActv_De_EmTqActv;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) TqSplt_10ms_Rp_EmTqReqMax_De_EmTqPosLimShoTerm;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) TqSplt_10ms_Rp_EmTqReqMin_De_EmTqNegLimShoTerm;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) TqSplt_10ms_Rp_VehSpdLgt_De_VehSpdLgt;
};
typedef struct Rte_CDS_TqSplt Rte_CDS_TqSplt;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(struct Rte_CDS_TqSplt, RTE_CONST) Rte_Inst_TqSplt;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_TqSplt, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE
#define RTE_START_SEC_VAR_CLEARED_32
#include "Rte_MemMap.h"
extern VAR(Rte_ImplicitBufsType, RTE_DATA) Rte_ImplicitBufs;
#define RTE_STOP_SEC_VAR_CLEARED_32
#include "Rte_MemMap.h"
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_TqSplt_10ms)
/* Inline read optimization; Rte_IRead_TqSplt_10ms_Rp_BrkReqd_De_BrkReqd to implicit access macro */
#define Rte_IRead_TqSplt_10ms_Rp_BrkReqd_De_BrkReqd()  ( (CONST(boolean, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf17.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_TqSplt_10ms)
/* Inline read optimization; Rte_IRead_TqSplt_10ms_Rp_DrvrTqReq_De_DrvrTqReq to implicit access macro */
#define Rte_IRead_TqSplt_10ms_Rp_DrvrTqReq_De_DrvrTqReq()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf18.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_TqSplt_10ms)
/* Inline read optimization; Rte_IRead_TqSplt_10ms_Rp_EmTqActv_De_EmTqActv to implicit access macro */
#define Rte_IRead_TqSplt_10ms_Rp_EmTqActv_De_EmTqActv()  ( (CONST(boolean, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf19.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_TqSplt_10ms)
/* Inline read optimization; Rte_IRead_TqSplt_10ms_Rp_EmTqReqMax_De_EmTqPosLimShoTerm to implicit access macro */
#define Rte_IRead_TqSplt_10ms_Rp_EmTqReqMax_De_EmTqPosLimShoTerm()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf20.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_TqSplt_10ms)
/* Inline read optimization; Rte_IRead_TqSplt_10ms_Rp_EmTqReqMin_De_EmTqNegLimShoTerm to implicit access macro */
#define Rte_IRead_TqSplt_10ms_Rp_EmTqReqMin_De_EmTqNegLimShoTerm()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf21.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_TqSplt_10ms)
/* Inline read optimization; Rte_IRead_TqSplt_10ms_Rp_VehSpdLgt_De_VehSpdLgt to implicit access macro */
#define Rte_IRead_TqSplt_10ms_Rp_VehSpdLgt_De_VehSpdLgt()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf22.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_TqSplt_10ms)
/* Inline write optimization; Rte_IWriteRef_TqSplt_10ms_Pp_EmTqReqLimd_De_EmTqReqLimd to implicit access macro */
#define Rte_IWriteRef_TqSplt_10ms_Pp_EmTqReqLimd_De_EmTqReqLimd()  ( (P2VAR(float32, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf15.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_TqSplt_10ms)
/* Inline write optimization; Rte_IWriteRef_TqSplt_10ms_Pp_FoudnBrkTqReq_De_FoudnBrkTqReq to implicit access macro */
#define Rte_IWriteRef_TqSplt_10ms_Pp_FoudnBrkTqReq_De_FoudnBrkTqReq()  ( (P2VAR(float32, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf16.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_TqSplt_10ms)
/* Inline write optimization; Rte_IWrite_TqSplt_10ms_Pp_EmTqReqLimd_De_EmTqReqLimd to implicit access macro */
#define Rte_IWrite_TqSplt_10ms_Pp_EmTqReqLimd_De_EmTqReqLimd( data )  ( Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf15.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_TqSplt_10ms)
/* Inline write optimization; Rte_IWrite_TqSplt_10ms_Pp_FoudnBrkTqReq_De_FoudnBrkTqReq to implicit access macro */
#define Rte_IWrite_TqSplt_10ms_Pp_FoudnBrkTqReq_De_FoudnBrkTqReq( data )  ( Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf16.value = (data) )
#endif

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define TqSplt_START_SEC_QmCode
#include "TqSplt_MemMap.h"
FUNC(void, TqSplt_QmCode) TqSplt_TqSplt_10ms(void);
FUNC(void, TqSplt_QmCode) TqSplt_TqSplt_Init(void);
#define TqSplt_STOP_SEC_QmCode
#include "TqSplt_MemMap.h"

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_TQSPLT_H */
