/** @file     Rte_Cbk.h
  *
  * @brief    RTE generated callbacks
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.0
  */

#ifndef RTE_CBK_H
#define RTE_CBK_H

/* ----- RTE Callback functions ----- */

#define RTE_SIG_S_PARKCONTROL_BOOL_CAN_NETWORK_CHANNEL_CAN_RX_START_SEC_CODE
#include "Rte_MemMap.h"
FUNC(void, RTE_CODE) Rte_COMCbk_S_ParkControl_bool_Can_Network_Channel_CAN_Rx(void);
#define RTE_SIG_S_PARKCONTROL_BOOL_CAN_NETWORK_CHANNEL_CAN_RX_STOP_SEC_CODE
#include "Rte_MemMap.h"

FUNC(void, RTE_CODE) Rte_COMCbk_Brake_Data(void);
FUNC(void, RTE_CODE) Rte_COMCbk_For_HIL_Test_Only_EPB_Status(void);
FUNC(void, RTE_CODE) Rte_COMCbk_For_HIL_Test_Only_PowerMode(void);
FUNC(void, RTE_CODE) Rte_COMCbk_For_HIL_Test_Only_VehicleState(void);
FUNC(void, RTE_CODE) Rte_COMCbk_Red_Button_01(void);
FUNC(void, RTE_CODE) Rte_COMCbk_Throttle_Data(void);
FUNC(void, RTE_CODE) Rte_COMCbk_nmCanPdRlNegTrqLim(void);
FUNC(void, RTE_CODE) Rte_COMCbk_nmCanPdRlPosTrqLim(void);
FUNC(void, RTE_CODE) Rte_COMCbk_nmCanPdRrNegTrqLim(void);
FUNC(void, RTE_CODE) Rte_COMCbk_nmCanPdRrPosTrqLim(void);
FUNC(void, RTE_CODE) Rte_COMCbk_rpmCanPdRlSpdEst(void);
FUNC(void, RTE_CODE) Rte_COMCbk_rpmCanPdRrSpdEst(void);
FUNC(void, RTE_CODE) Rte_COMCbk_sttBMS_AllowedDischCurrent(void);
FUNC(void, RTE_CODE) Rte_COMCbk_sttBMS_AllowedRegenCurrent(void);
FUNC(void, RTE_CODE) Rte_COMCbk_sttBMS_PackVoltage(void);

#endif /* !RTE_CBK_H */
