/** @file     Rte_DrvrItp.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.3.0 
  */

#ifndef RTE_DRVRITP_H
#define RTE_DRVRITP_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_DrvrItp_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_DrvrItp_10ms)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#elif defined(RTE_RUNNABLEAPI_DrvrItp_Init)
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/


/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_DrvrItp {
   /* Data handles */
   P2VAR(Rte_DE_boolean, AUTOMATIC, RTE_DATA) DrvrItp_10ms_Pp_BrkAppld_De_BrkAppld;
   P2VAR(Rte_DE_boolean, AUTOMATIC, RTE_DATA) DrvrItp_10ms_Pp_BrkReqd_De_BrkReqd;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) DrvrItp_10ms_Pp_DrvrTqReq_De_DrvrTqReq;
   P2VAR(Rte_DE_uint8  , AUTOMATIC, RTE_DATA) DrvrItp_10ms_Rp_DlnSt_De_DlnSt;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) DrvrItp_10ms_Rp_JstkYpos_De_JstkYpos;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) DrvrItp_10ms_Rp_VehSpdLgt_De_VehSpdLgt;
};
typedef struct Rte_CDS_DrvrItp Rte_CDS_DrvrItp;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(struct Rte_CDS_DrvrItp, RTE_CONST) Rte_Inst_DrvrItp;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_DrvrItp, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE
#define RTE_START_SEC_VAR_CLEARED_32
#include "Rte_MemMap.h"
extern VAR(Rte_ImplicitBufsType, RTE_DATA) Rte_ImplicitBufs;
#define RTE_STOP_SEC_VAR_CLEARED_32
#include "Rte_MemMap.h"
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DrvrItp_10ms)
/* Inline read optimization; Rte_IRead_DrvrItp_10ms_Rp_DlnSt_De_DlnSt to implicit access macro */
#define Rte_IRead_DrvrItp_10ms_Rp_DlnSt_De_DlnSt()  ( (CONST(uint8, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf28.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DrvrItp_10ms)
/* Inline read optimization; Rte_IRead_DrvrItp_10ms_Rp_JstkYpos_De_JstkYpos to implicit access macro */
#define Rte_IRead_DrvrItp_10ms_Rp_JstkYpos_De_JstkYpos()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf26.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DrvrItp_10ms)
/* Inline read optimization; Rte_IRead_DrvrItp_10ms_Rp_VehSpdLgt_De_VehSpdLgt to implicit access macro */
#define Rte_IRead_DrvrItp_10ms_Rp_VehSpdLgt_De_VehSpdLgt()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf22.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DrvrItp_10ms)
/* Inline write optimization; Rte_IWriteRef_DrvrItp_10ms_Pp_BrkAppld_De_BrkAppld to implicit access macro */
#define Rte_IWriteRef_DrvrItp_10ms_Pp_BrkAppld_De_BrkAppld()  ( (P2VAR(boolean, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf32.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DrvrItp_10ms)
/* Inline write optimization; Rte_IWriteRef_DrvrItp_10ms_Pp_BrkReqd_De_BrkReqd to implicit access macro */
#define Rte_IWriteRef_DrvrItp_10ms_Pp_BrkReqd_De_BrkReqd()  ( (P2VAR(boolean, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf17.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DrvrItp_10ms)
/* Inline write optimization; Rte_IWriteRef_DrvrItp_10ms_Pp_DrvrTqReq_De_DrvrTqReq to implicit access macro */
#define Rte_IWriteRef_DrvrItp_10ms_Pp_DrvrTqReq_De_DrvrTqReq()  ( (P2VAR(float32, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf18.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DrvrItp_10ms)
/* Inline write optimization; Rte_IWrite_DrvrItp_10ms_Pp_BrkAppld_De_BrkAppld to implicit access macro */
#define Rte_IWrite_DrvrItp_10ms_Pp_BrkAppld_De_BrkAppld( data )  ( Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf32.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DrvrItp_10ms)
/* Inline write optimization; Rte_IWrite_DrvrItp_10ms_Pp_BrkReqd_De_BrkReqd to implicit access macro */
#define Rte_IWrite_DrvrItp_10ms_Pp_BrkReqd_De_BrkReqd( data )  ( Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf17.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_DrvrItp_10ms)
/* Inline write optimization; Rte_IWrite_DrvrItp_10ms_Pp_DrvrTqReq_De_DrvrTqReq to implicit access macro */
#define Rte_IWrite_DrvrItp_10ms_Pp_DrvrTqReq_De_DrvrTqReq( data )  ( Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf18.value = (data) )
#endif

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define DrvrItp_START_SEC_QmCode
#include "DrvrItp_MemMap.h"
FUNC(void, DrvrItp_QmCode) DrvrItp_DrvrItp_10ms(void);
FUNC(void, DrvrItp_QmCode) DrvrItp_DrvrItp_Init(void);
#define DrvrItp_STOP_SEC_QmCode
#include "DrvrItp_MemMap.h"

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_DRVRITP_H */
