/** @file     Rte_SystemSWC_Type.h
  *
  * @brief    Application types header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.0
  */

#ifndef RTE_SystemSWC_TYPE_H
#define RTE_SystemSWC_TYPE_H

#include "Rte_Type.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* BEGIN: SWC specific types */
#ifndef RTE_CORE
#ifndef RTE_MODETYPE_MDG_SHUTDOWN
#define RTE_MODETYPE_MDG_SHUTDOWN

typedef uint8 Rte_ModeType_MDG_ShutDown;

#endif /* !RTE_MODETYPE_MDG_SHUTDOWN */
#endif /* RTE_CORE */

/* END: SWC specific types */

/* BEGIN: SWC specific definitions */
#ifndef RTE_CORE
#ifndef RTE_MODE_MDG_ShutDown_RUN
#define RTE_MODE_MDG_ShutDown_RUN                1U
#endif /* !RTE_MODE_MDG_ShutDown_RUN */
#ifndef RTE_MODE_MDG_ShutDown_SHUT_DOWN
#define RTE_MODE_MDG_ShutDown_SHUT_DOWN          0U
#endif /* !RTE_MODE_MDG_ShutDown_SHUT_DOWN */
#ifndef RTE_TRANSITION_MDG_ShutDown
#define RTE_TRANSITION_MDG_ShutDown              2U
#endif /* !RTE_TRANSITION_MDG_ShutDown */
#endif /* RTE_CORE */

#if !defined(RTE_CORE)

/* Box: /ImplementationDataTypes/KeyState begin */
/* Box: CompuScale ("KEY_OFF") begin */
#ifndef KEY_OFF
#define KEY_OFF (0U)
#endif /* !KEY_OFF */
/* Box: CompuScale ("KEY_OFF") end */
/* Box: CompuScale_0 ("KEY_ON") begin */
#ifndef KEY_ON
#define KEY_ON (1U)
#endif /* !KEY_ON */
/* Box: CompuScale_0 ("KEY_ON") end */
/* Box: CompuScale_1 ("KEY_STATE2") begin */
#ifndef KEY_STATE2
#define KEY_STATE2 (2U)
#endif /* !KEY_STATE2 */
/* Box: CompuScale_1 ("KEY_STATE2") end */
/* Box: CompuScale_2 ("KEY_STATE3") begin */
#ifndef KEY_STATE3
#define KEY_STATE3 (3U)
#endif /* !KEY_STATE3 */
/* Box: CompuScale_2 ("KEY_STATE3") end */
/* Box: /ImplementationDataTypes/KeyState end */
#endif /* !defined(RTE_CORE) */
/* END: SWC specific definitions */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_SystemSWC_TYPE_H */
