/** @file     Rte_ComM.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.0
  */

#ifndef RTE_COMM_H
#define RTE_COMM_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_ComM_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_GetCurrentComMode)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#elif defined(RTE_RUNNABLEAPI_GetMaxComMode)
#elif defined(RTE_RUNNABLEAPI_GetRequestedComMode)
#elif defined(RTE_RUNNABLEAPI_MainFunction_Can_Network_Channel_Can_Network)
#elif defined(RTE_RUNNABLEAPI_MainFunction_ComMChannel_Can_Network_0_Channel)
#elif defined(RTE_RUNNABLEAPI_MainFunction_ComMChannel_Can_Network_1_Channel)
#elif defined(RTE_RUNNABLEAPI_MainFunction_ComMChannel_Can_Network_2_Channel)
#elif defined(RTE_RUNNABLEAPI_MainFunction_ComMChannel_Can_Network_3_Channel)
#elif defined(RTE_RUNNABLEAPI_MainFunction_ComMChannel_Can_Network_4_Channel)
#elif defined(RTE_RUNNABLEAPI_RequestComMode)
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/


/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_ComM {
   uint8 Rte_Dummy;
};
typedef struct Rte_CDS_ComM Rte_CDS_ComM;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(struct Rte_CDS_ComM, RTE_CONST) Rte_Inst_ComM;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_ComM, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/


/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_COMM_H */
