/** @file     Rte_EmTqFil.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.3.0 
  */

#ifndef RTE_EMTQFIL_H
#define RTE_EMTQFIL_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_EmTqFil_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_EmTqFil_10ms)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#elif defined(RTE_RUNNABLEAPI_EmTqFil_Init)
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/


/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_EmTqFil {
   /* Data handles */
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) EmTqFil_10ms_Pp_EmTqReqReLe_De_EmTqReqReLe;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) EmTqFil_10ms_Pp_EmTqReqReRi_De_EmTqReqReRi;
   P2VAR(Rte_DE_uint8  , AUTOMATIC, RTE_DATA) EmTqFil_10ms_Rp_DlnSt_De_DlnSt;
   P2VAR(Rte_DE_float32, AUTOMATIC, RTE_DATA) EmTqFil_10ms_Rp_EmTqReqLimd_De_EmTqReqLimd;
};
typedef struct Rte_CDS_EmTqFil Rte_CDS_EmTqFil;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(struct Rte_CDS_EmTqFil, RTE_CONST) Rte_Inst_EmTqFil;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_EmTqFil, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE
#define RTE_START_SEC_VAR_CLEARED_32
#include "Rte_MemMap.h"
extern VAR(Rte_ImplicitBufsType, RTE_DATA) Rte_ImplicitBufs;
#define RTE_STOP_SEC_VAR_CLEARED_32
#include "Rte_MemMap.h"
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EmTqFil_10ms)
/* Inline read optimization; Rte_IRead_EmTqFil_10ms_Rp_DlnSt_De_DlnSt to implicit access macro */
#define Rte_IRead_EmTqFil_10ms_Rp_DlnSt_De_DlnSt()  ( (CONST(uint8, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf28.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EmTqFil_10ms)
/* Inline read optimization; Rte_IRead_EmTqFil_10ms_Rp_EmTqReqLimd_De_EmTqReqLimd to implicit access macro */
#define Rte_IRead_EmTqFil_10ms_Rp_EmTqReqLimd_De_EmTqReqLimd()  ( (CONST(float32, RTE_DATA)) Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf15.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EmTqFil_10ms)
/* Inline write optimization; Rte_IWriteRef_EmTqFil_10ms_Pp_EmTqReqReLe_De_EmTqReqReLe to implicit access macro */
#define Rte_IWriteRef_EmTqFil_10ms_Pp_EmTqReqReLe_De_EmTqReqReLe()  ( (P2VAR(float32, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf30.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EmTqFil_10ms)
/* Inline write optimization; Rte_IWriteRef_EmTqFil_10ms_Pp_EmTqReqReRi_De_EmTqReqReRi to implicit access macro */
#define Rte_IWriteRef_EmTqFil_10ms_Pp_EmTqReqReRi_De_EmTqReqReRi()  ( (P2VAR(float32, AUTOMATIC, RTE_DATA)) &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf31.value )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EmTqFil_10ms)
/* Inline write optimization; Rte_IWrite_EmTqFil_10ms_Pp_EmTqReqReLe_De_EmTqReqReLe to implicit access macro */
#define Rte_IWrite_EmTqFil_10ms_Pp_EmTqReqReLe_De_EmTqReqReLe( data )  ( Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf30.value = (data) )
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_EmTqFil_10ms)
/* Inline write optimization; Rte_IWrite_EmTqFil_10ms_Pp_EmTqReqReRi_De_EmTqReqReRi to implicit access macro */
#define Rte_IWrite_EmTqFil_10ms_Pp_EmTqReqReRi_De_EmTqReqReRi( data )  ( Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW_PeriodicEvents.sbuf31.value = (data) )
#endif

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define EmTqFil_START_SEC_QmCode
#include "EmTqFil_MemMap.h"
FUNC(void, EmTqFil_QmCode) EmTqFil_EmTqFil_10ms(void);
FUNC(void, EmTqFil_QmCode) EmTqFil_EmTqFil_Init(void);
#define EmTqFil_STOP_SEC_QmCode
#include "EmTqFil_MemMap.h"

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_EMTQFIL_H */
