/** @file     Rte_DrvrItp_Type.h
  *
  * @brief    Application types header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.3.0 
  */

#ifndef RTE_DrvrItp_TYPE_H
#define RTE_DrvrItp_TYPE_H

#include "Rte_Type.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* BEGIN: SWC specific types */
/* END: SWC specific types */

/* BEGIN: SWC specific definitions */
#if !defined(RTE_CORE)

/* Box: /VCU_Software_pkg/software_config/DataTypes/ApplicationDataTypes/DlnStEnum begin */
/* Box: "DlnSt_Park" begin */
#ifndef DlnSt_Park
#define DlnSt_Park (0U)
#endif /* !DlnSt_Park */
/* Box: "DlnSt_Park" end */
/* Box: "DlnSt_Rvs" begin */
#ifndef DlnSt_Rvs
#define DlnSt_Rvs (1U)
#endif /* !DlnSt_Rvs */
/* Box: "DlnSt_Rvs" end */
/* Box: "DlnSt_Neut" begin */
#ifndef DlnSt_Neut
#define DlnSt_Neut (2U)
#endif /* !DlnSt_Neut */
/* Box: "DlnSt_Neut" end */
/* Box: "DlnSt_Drv" begin */
#ifndef DlnSt_Drv
#define DlnSt_Drv (3U)
#endif /* !DlnSt_Drv */
/* Box: "DlnSt_Drv" end */
/* Box: /VCU_Software_pkg/software_config/DataTypes/ApplicationDataTypes/DlnStEnum end */

/* Box: /VCU_Software_pkg/software_config/DataTypes/ImplementationDataTypes/boolean begin */
/* Box: "FALSE" begin */
#ifndef FALSE
#define FALSE (0U)
#endif /* !FALSE */
/* Box: "FALSE" end */
/* Box: "TRUE" begin */
#ifndef TRUE
#define TRUE (1U)
#endif /* !TRUE */
/* Box: "TRUE" end */
/* Box: /VCU_Software_pkg/software_config/DataTypes/ImplementationDataTypes/boolean end */
#endif /* !defined(RTE_CORE) */
/* END: SWC specific definitions */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_DrvrItp_TYPE_H */
