/** @file     Rte_TqSplt_Type.h
  *
  * @brief    Application types header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.3.0 
  */

#ifndef RTE_TqSplt_TYPE_H
#define RTE_TqSplt_TYPE_H

#include "Rte_Type.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* BEGIN: SWC specific types */
/* END: SWC specific types */

/* BEGIN: SWC specific definitions */
#if !defined(RTE_CORE)

/* Box: /VCU_Software_pkg/software_config/DataTypes/ImplementationDataTypes/boolean begin */
/* Box: "FALSE" begin */
#ifndef FALSE
#define FALSE (0U)
#endif /* !FALSE */
/* Box: "FALSE" end */
/* Box: "TRUE" begin */
#ifndef TRUE
#define TRUE (1U)
#endif /* !TRUE */
/* Box: "TRUE" end */
/* Box: /VCU_Software_pkg/software_config/DataTypes/ImplementationDataTypes/boolean end */
#endif /* !defined(RTE_CORE) */
/* END: SWC specific definitions */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_TqSplt_TYPE_H */
